package GenericDSL.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Child = 0;
  public static final int IContent = 1;
  public static final int Parent = 2;
  public static final int Root = 3;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x7a5361d88b2b4f3aL, 0xa89a5c606c9b345bL);
    builder.put(0x58025e95ca9c6829L, Child);
    builder.put(0x58025e95ca9c6824L, IContent);
    builder.put(0x58025e95ca9c6820L, Parent);
    builder.put(0x58025e95ca9c6823L, Root);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
